/*
usermng

usermng api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BindDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BindDeviceRequest{}

// BindDeviceRequest struct for BindDeviceRequest
type BindDeviceRequest struct {
	DeviceId string `json:"deviceId"`
}

type _BindDeviceRequest BindDeviceRequest

// NewBindDeviceRequest instantiates a new BindDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBindDeviceRequest(deviceId string) *BindDeviceRequest {
	this := BindDeviceRequest{}
	this.DeviceId = deviceId
	return &this
}

// NewBindDeviceRequestWithDefaults instantiates a new BindDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBindDeviceRequestWithDefaults() *BindDeviceRequest {
	this := BindDeviceRequest{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *BindDeviceRequest) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *BindDeviceRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *BindDeviceRequest) SetDeviceId(v string) {
	o.DeviceId = v
}

func (o BindDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BindDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deviceId"] = o.DeviceId
	return toSerialize, nil
}

func (o *BindDeviceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deviceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBindDeviceRequest := _BindDeviceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBindDeviceRequest)

	if err != nil {
		return err
	}

	*o = BindDeviceRequest(varBindDeviceRequest)

	return err
}

type NullableBindDeviceRequest struct {
	value *BindDeviceRequest
	isSet bool
}

func (v NullableBindDeviceRequest) Get() *BindDeviceRequest {
	return v.value
}

func (v *NullableBindDeviceRequest) Set(val *BindDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBindDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBindDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBindDeviceRequest(val *BindDeviceRequest) *NullableBindDeviceRequest {
	return &NullableBindDeviceRequest{value: val, isSet: true}
}

func (v NullableBindDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBindDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


